Controllers/RoutesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebTestExample.Objects;

namespace WebTestExample.Controllers
{
    public class RoutesController : Controller
    {
        /// <summary>  
        ///  Route to home page and get init data for homepage
        /// </summary>  
        public ActionResult Index()
        {
            try
            {
                ViewBag.Title = "Home Page"; // Set Page Title

                //Check if active valid session is available otherwise redirect to Login page
                if (!App_Global.GlbSessionVariables.ValidSession)
                {
                    Response.RedirectToRoute("Login");
                }
                else
                {
                    //Get initialise Data for home page
                    
                    HomePageObject tempHomeObj = ShopController.InitHomeValues();
                    ViewData["HomePageObject"] = tempHomeObj; // Add init data to viewBag
                    return View();
                }
                
                //Open home page
                return View();
            }
            catch (Exception e)
            {

                throw e;
            }

        }

        /// <summary>  
        /// Route to login page
        /// </summary>  
        public ActionResult Login()
        {
            ViewBag.Title = "Login Page";

            return View();
        }

        /// <summary>  
        /// Route to registration page
        /// </summary>  
        public ActionResult Register()
        {
            ViewBag.Title = "Register Page";

            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
@using WebTestExample.App_Global;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
        @if (@GlbSessionVariables.LoggedInUserID > 0 || @GlbSessionVariables.LoggedInUserID == @GlbSessionVariables.AdminUserID)
        {
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">


                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        @Html.ActionLink("Mukuru", "Index", "Routes", new { area = "" }, new { @class = "navbar-brand" })
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li> <a>Welcome : @GlbSessionVariables.LoggedInUserName</a> </li>
                            <li class="pull-right"> <a href="api/shop/currency/update"> Sync Currencies </a> </li>
                        </ul>
                    </div>
               
                </div>
            </div>
         }
        <div class="container body-content" style="margin-top:30px">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Mukuru</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/custom")
        @RenderSection("scripts", required: false)
    </body>
</html>